### ISSUE TITLE
Application has thrown an uncaught exception and is terminated: Error: Cannot find module './lib'

### ISSUE THREAD

**Issue by fadyham** [Surnet/swagger-jsdoc#243]
This npm package used to work in version 4.0.0, but is broken after version 5 I believe.  It's still broken in version 6.0.2.  Here's the full exception:

Sun Feb 07 2021 07:49:28 GMT+0000 (Greenwich Mean Time): Application has thrown an uncaught exception and is terminated: Error: Cannot find module './lib'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object.<anonymous> (D:\home\site\wwwroot\node_modules\swagger-jsdoc\index.js:1:80)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Note that when I revert back to version 4.0.0, I find a "lib" folder in: node_modules\swagger-jsdoc
The broken versions do not have the "lib" directory.

**Comment by kalinchernev** [comment]
Could you please let me know which version of node and npm you're using?
Also, have you tried removing the node_modules folder and re-installing?

**Comment by fadyham** [comment]
Note that this issue doesn't repo locally.  The app only crashes when I deploy to Azure App Service
Here are my version on Azure:
npm 6.4.1
node v10.15.2

Here are my versions locally:
npm 6.12.0
node v10.15.0

I have cleaned the enlistment in between upgrades/downgrades including the removal of the node_modules folder.  This is where I noticed that the lib folder is not in the later versions of node_modules\swagger-jsdoc

**Comment by kalinchernev** [comment]
If the issue appears only on your cloud hosting and not locally this means it's an issue with the platform. 

Check these: 
- v5 https://github.com/Surnet/swagger-jsdoc/blob/v5/package.json#L14, https://github.com/Surnet/swagger-jsdoc/blob/v5/index.js and https://github.com/Surnet/swagger-jsdoc/blob/v5/src/lib.js#L17
- v6 is the same

If you use containers or any similar technology, double-check volumes mounting an mapping to ensure that files installed in node_modules are made available in the containerized application.

**Comment by fadyham** [comment]
index.js and src/lib.js are available on the deployed environment.  Here's the full list on azure:
**when installing swagger-jsdoc@4.0.0:**

D:\home\site\wwwroot\node_modules\swagger-jsdoc>dir /s
 Volume in drive D is Windows
 Volume Serial Number is B492-AC54

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc

02/07/2021  10:52 PM    <DIR>          .
02/07/2021  10:52 PM    <DIR>          ..
10/26/1985  08:15 AM                13 .eslintignore
10/26/1985  08:15 AM               161 .eslintrc.js
10/26/1985  08:15 AM                65 .mocharc.yml
10/26/1985  08:15 AM                12 .nvmrc
10/26/1985  08:15 AM                32 .prettierignore
10/26/1985  08:15 AM                45 .prettierrc
02/07/2021  08:45 PM    <DIR>          bin
10/26/1985  08:15 AM                35 index.js
02/07/2021  10:52 PM    <DIR>          lib
10/26/1985  08:15 AM             1,156 LICENSE
02/07/2021  10:55 PM             2,436 package.json
10/26/1985  08:15 AM             7,472 README.md
              10 File(s)         11,427 bytes

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc\bin

02/07/2021  08:45 PM    <DIR>          .
02/07/2021  08:45 PM    <DIR>          ..
10/26/1985  08:15 AM             4,822 swagger-jsdoc.js
               1 File(s)          4,822 bytes

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc\lib

02/07/2021  10:52 PM    <DIR>          .
02/07/2021  10:52 PM    <DIR>          ..
02/07/2021  10:52 PM    <DIR>          helpers
10/26/1985  08:15 AM             1,516 index.js
               1 File(s)          1,516 bytes

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc\lib\helpers

02/07/2021  10:52 PM    <DIR>          .
02/07/2021  10:52 PM    <DIR>          ..
10/26/1985  08:15 AM               427 convertGlobPaths.js
10/26/1985  08:15 AM             1,275 createSpecification.js
10/26/1985  08:15 AM               720 filterJsDocComments.js
10/26/1985  08:15 AM             1,382 finalizeSpecificationObject.js
10/26/1985  08:15 AM               932 getSpecificationObject.js
10/26/1985  08:15 AM               407 hasEmptyProperty.js
10/26/1985  08:15 AM               521 parseApiFile.js
10/26/1985  08:15 AM               967 parseApiFileContent.js
10/26/1985  08:15 AM             4,849 specification.js
10/26/1985  08:15 AM               612 updateSpecificationObject.js
              10 File(s)         12,092 bytes

     Total Files Listed:
              22 File(s)         29,857 bytes
              11 Dir(s)     930,516,992 bytes free


**With swagger-jsdoc@6.0.2:**
D:\home\site\wwwroot\node_modules\swagger-jsdoc>dir /s
 Volume in drive D is Windows
 Volume Serial Number is B492-AC54

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc

02/08/2021  08:48 AM    <DIR>          .
02/08/2021  08:48 AM    <DIR>          ..
02/07/2021  08:45 PM    <DIR>          bin
10/26/1985  08:15 AM            48,609 CHANGELOG.md
10/26/1985  08:15 AM                35 index.js
10/26/1985  08:15 AM             1,156 LICENSE
02/08/2021  08:33 AM             2,425 package.json
10/26/1985  08:15 AM             7,472 README.md
02/08/2021  08:48 AM    <DIR>          src
               5 File(s)         59,697 bytes

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc\bin

02/07/2021  08:45 PM    <DIR>          .
02/07/2021  08:45 PM    <DIR>          ..
10/26/1985  08:15 AM             4,822 swagger-jsdoc.js
               1 File(s)          4,822 bytes

 Directory of D:\home\site\wwwroot\node_modules\swagger-jsdoc\src

02/08/2021  08:48 AM    <DIR>          .
02/08/2021  08:48 AM    <DIR>          ..
10/26/1985  08:15 AM             1,017 lib.js
10/26/1985  08:15 AM             7,924 specification.js
10/26/1985  08:15 AM             3,634 utils.js
               3 File(s)         12,575 bytes

     Total Files Listed:
               9 File(s)         77,094 bytes
               8 Dir(s)     929,263,616 bytes free

**Comment by kalinchernev** [comment]
@fadyham i just published a new patch version with the following contents

```
npm notice 📦  swagger-jsdoc@6.0.5
npm notice === Tarball Contents === 
npm notice 1.2kB  LICENSE             
npm notice 39B    index.js            
npm notice 1.0kB  src/lib.js          
npm notice 7.9kB  src/specification.js
npm notice 2.0kB  bin/swagger-jsdoc.js
npm notice 3.7kB  src/utils.js        
npm notice 1.7kB  package.json        
npm notice 49.0kB CHANGELOG.md        
npm notice 2.5kB  README.md
```

I don't see anything which can lead me to finding the issue with the state of your system at latest comment. 
Can you please try using the latest? Could you please also double-check if there are no specific symlink configurations on the hosting side?

**Comment by fadyham** [comment]
Just upgraded to swagger-jsdoc@6.0.5 and installed the peer dependency openapi-types@7.2.3.  Same error.  Note that the output still has the lib.js file but is missing the lib directory that was present in older versions of swagger-jsdoc.  I believe as long as this directory is missing, it won't work for me.

Here's my tsconfig if that helps:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "./dist",
    "target": "es6",
    "lib": [ "es6", "dom" ],
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "rootDirs": [
      "src"
    ]
  },
  "exclude": [
    "node_modules"
  ],
}
```

**Comment by kalinchernev** [comment]
@fadyham I am afraid I cannot help more than making the checks I've already made.
Regarding typescript, I have very little experience with it and swagger-jsdoc is written without it. I don't know why and how you use the typescript so I can't help with configurations.
Reading through the history of comments here, it feels like you have done customization either on the building part or the deployment part which changes the folder structure of the library and it does not work any more.
At any case, swagger-jsdoc is not meant to be recompiled (or even compiled) at the moment. With all versions up to 6, the commonjs module system has been used and i, again, i don't have enough context to help at the moment.
If you manage to extract parts of your project and create a sample repo where we can investigate the output compiler and compare what goes where i might be able to help, but out of that i am not
